version: '3.9'

# provide a docker-compose file for a node.js application with nginx, postgres and redis
services:
  # the redis database
  redis:
    image: redis
    volumes:
      - ./redis-data:/data
  # the node.js application
  backend_1:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
      - CLERK_API_KEY=${CLERK_API_KEY}
  # the nginx reverse proxy
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend_1
  # the postgres database
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hockeypool
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"